export const CATEGORY_STYLE = {
  Memory: { color: "#60a5fa", bg: "rgba(96,165,250,0.10)" },
  Attention: { color: "#f59e0b", bg: "rgba(245,158,11,0.10)" },
  "Problem Solving": { color: "#a78bfa", bg: "rgba(167,139,250,0.10)" },
};

export const GAMES = [
  {
    id: "game-story-reconstruct",
    title: "Story Fragment Reconstruction",
    category: "Memory",
    icon: "📖",
    difficulty: "Medium",
    measures: "Episodic memory, temporal sequencing, context retention",
    questions: [
      { q: "Story order: 1) Rain started 2) She opened umbrella 3) She reached bus stop. What comes second?", options: ["Rain started", "She opened umbrella", "She reached bus stop", "She returned home"], answer: 1 },
      { q: "Which event happened first in: alarm rang -> brushed teeth -> left home -> caught train?", options: ["Caught train", "Brushed teeth", "Alarm rang", "Left home"], answer: 2 },
      { q: "If sentence C is 'He paid the bill', what likely comes before it?", options: ["He entered restaurant", "He drove away", "He slept", "He watched TV"], answer: 0 },
      { q: "Best ending after: packed bag -> locked door -> walked to gate -> ?", options: ["Unpacked bag", "Returned inside", "Reached the road", "Went to sleep"], answer: 2 },
      { q: "Temporal clue: 'After lunch, she wrote notes.' What came before writing notes?", options: ["Lunch", "Dinner", "Sleep", "Commute"], answer: 0 },
    ],
  },
  {
    id: "game-face-name",
    title: "Face-Name Association",
    category: "Memory",
    icon: "🧑",
    difficulty: "Medium",
    measures: "Associative memory, social memory, encoding accuracy",
    questions: [
      { q: "Face A was paired with which name?", options: ["Riya", "Aman", "Neha", "Kabir"], answer: 0 },
      { q: "Face B belonged to:", options: ["Sana", "Ishaan", "Rohit", "Meera"], answer: 3 },
      { q: "You learned: Arjun-Blue shirt, Kavya-Red shirt. Red shirt is:", options: ["Arjun", "Kavya", "Neither", "Both"], answer: 1 },
      { q: "If Nina had glasses in study phase, who had glasses?", options: ["Nina", "Dev", "Anika", "Zoya"], answer: 0 },
      { q: "Who was paired with Face E?", options: ["Aarav", "Pooja", "Zain", "Rekha"], answer: 2 },
    ],
  },
  {
    id: "game-audio-tone",
    title: "Audio Tone Recall",
    category: "Memory",
    icon: "🎵",
    difficulty: "Hard",
    measures: "Auditory working memory, sequential recall, processing consistency",
    questions: [
      { q: "Sequence was High-Low-High. What is position 2?", options: ["High", "Low", "Silence", "Both"], answer: 1 },
      { q: "Recall: Low-High-Low-Low. Last tone was:", options: ["High", "Low", "None", "Unknown"], answer: 1 },
      { q: "If sequence starts High-High-Low, tone 3 is:", options: ["High", "Low", "Mute", "Mixed"], answer: 1 },
      { q: "Pattern Low-High-Low repeats. Next after Low-High-Low is:", options: ["High", "Low", "Low-High", "Pause"], answer: 0 },
      { q: "Which has two consecutive highs?", options: ["H-L-H", "L-H-L", "H-H-L", "L-L-H"], answer: 2 },
    ],
  },
  {
    id: "game-rhythm-sync",
    title: "Rhythm Sync Tap",
    category: "Attention",
    icon: "🥁",
    difficulty: "Medium",
    measures: "Sustained attention, motor-attention coordination, reaction stability",
    questions: [
      { q: "Beat interval is 500ms. Closer tap is:", options: ["480ms", "300ms", "900ms", "1200ms"], answer: 0 },
      { q: "You consistently tap late by 120ms. This reflects:", options: ["Better sync", "Timing drift", "No pattern", "Faster processing"], answer: 1 },
      { q: "Most stable rhythm is shown by:", options: ["200, 600, 1000ms gaps", "500, 510, 495ms gaps", "300, 900, 400ms gaps", "800, 200, 700ms gaps"], answer: 1 },
      { q: "If tempo increases, ideal response is:", options: ["Keep old speed", "Adapt tap speed faster", "Stop tapping", "Random tapping"], answer: 1 },
      { q: "Low tap variance usually indicates:", options: ["Poor focus", "Strong rhythm consistency", "Missed beats", "Motor freeze"], answer: 1 },
    ],
  },
  {
    id: "game-countdown-interrupt",
    title: "Countdown Interrupt",
    category: "Attention",
    icon: "⏱️",
    difficulty: "Hard",
    measures: "Vigilance, alertness, response inhibition",
    questions: [
      { q: "During 10..1 countdown, signal appears at 6. Correct action:", options: ["Ignore", "Immediate response", "Wait till 1", "Respond twice"], answer: 1 },
      { q: "False signal appears (different color). Best response:", options: ["Tap anyway", "Inhibit response", "Double tap", "Exit test"], answer: 1 },
      { q: "Frequent misses on rare signals suggest:", options: ["Strong vigilance", "Reduced vigilance", "Better inhibition", "Motor dominance"], answer: 1 },
      { q: "Fast but wrong responses indicate:", options: ["Impulsivity", "Perfect attention", "Semantic deficit", "Motor fatigue only"], answer: 0 },
      { q: "Best attention profile is:", options: ["Fast + accurate", "Slow + inaccurate", "Fast + many false alarms", "Misses all rare signals"], answer: 0 },
    ],
  },
  {
    id: "game-multi-rule-sort",
    title: "Multi-Rule Sorting",
    category: "Attention",
    icon: "🧩",
    difficulty: "Hard",
    measures: "Selective attention, rule maintenance, switching accuracy",
    questions: [
      { q: "Rule is COLOR. Red triangle should be sorted by:", options: ["Triangle", "Red", "Size", "Position"], answer: 1 },
      { q: "Rule switches to SHAPE without warning. Blue circle now sorted by:", options: ["Blue", "Circle", "Brightness", "Speed"], answer: 1 },
      { q: "Correct behavior after rule switch is:", options: ["Continue old rule", "Adapt to new rule", "Random sort", "Skip item"], answer: 1 },
      { q: "Errors right after rule switch usually indicate:", options: ["Set-shifting challenge", "Perfect maintenance", "No cognitive load", "Only visual issue"], answer: 0 },
      { q: "Lower switch cost means:", options: ["Better cognitive flexibility", "Poor inhibition", "Slower processing", "Higher impulsivity"], answer: 0 },
    ],
  },
  {
    id: "game-gk-logic",
    title: "Timed GK Logic Challenge",
    category: "Problem Solving",
    icon: "🌍",
    difficulty: "Medium",
    measures: "Semantic memory, retrieval speed, logical elimination, processing time",
    questions: [
      { q: "Closest planet to the Sun?", options: ["Venus", "Mercury", "Earth", "Mars"], answer: 1 },
      { q: "Country using Yen as currency?", options: ["China", "Korea", "Japan", "Thailand"], answer: 2 },
      { q: "Arrange earliest to latest: WW1, WW2, Moon Landing", options: ["WW2, WW1, Moon", "WW1, WW2, Moon", "Moon, WW1, WW2", "WW1, Moon, WW2"], answer: 1 },
      { q: "Largest ocean?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], answer: 3 },
      { q: "Logical odd one out: Oxygen, Nitrogen, Helium, Water", options: ["Oxygen", "Nitrogen", "Helium", "Water"], answer: 3 },
    ],
  },
  {
    id: "game-calc-sprint",
    title: "Mental Calculation Sprint",
    category: "Problem Solving",
    icon: "🔢",
    difficulty: "Hard",
    measures: "Working memory, numerical reasoning, processing speed, executive function",
    questions: [
      { q: "27 x 3 =", options: ["81", "72", "69", "84"], answer: 0 },
      { q: "144 / 12 =", options: ["10", "12", "14", "16"], answer: 1 },
      { q: "15% of 200 =", options: ["20", "25", "30", "35"], answer: 2 },
      { q: "Series: 2, 6, 18, ?", options: ["36", "48", "54", "72"], answer: 2 },
      { q: "45 + 39 =", options: ["74", "84", "94", "88"], answer: 1 },
    ],
  },
  {
    id: "game-decision-sim",
    title: "Real-Life Decision Simulation",
    category: "Problem Solving",
    icon: "🧠",
    difficulty: "Medium",
    measures: "Applied numeracy, planning, practical reasoning, judgment",
    questions: [
      { q: "Budget 1000, groceries 850, 10% discount above 900. Best move?", options: ["Buy only 850", "Add item to cross 900 then discount", "Spend all 1000 randomly", "Cancel shopping"], answer: 1 },
      { q: "30 minutes, 3 tasks. Best strategy?", options: ["Do hardest last", "Prioritize highest impact first", "Start random", "Do easiest only"], answer: 1 },
      { q: "Two routes: 20 min with toll, 35 min free. Need urgent arrival.", options: ["Free route", "Toll route", "Wait 10 min", "Cancel trip"], answer: 1 },
      { q: "Medicine reminder set for 8 PM daily. Best adherence method?", options: ["Rely on memory", "Use alarm + pill box", "Take anytime", "Skip when busy"], answer: 1 },
      { q: "Meeting in 15 min, commute 20 min. Best decision?", options: ["Start now and inform delay", "Do nothing", "Arrive late silently", "Cancel without notice"], answer: 0 },
    ],
  },
];

export const GAME_IDS = GAMES.map(g => g.id);
